#!/bin/bash
# install.sh - shipready v1.0.0
# Complete environment setup for production-ready applications
# Usage: ./install.sh [project-name]

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Print colored messages
print_step() {
    echo -e "${BLUE}==>${NC} ${GREEN}$1${NC}"
}

print_error() {
    echo -e "${RED}❌ Error:${NC} $1"
    exit 1
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

# Check for required tools
check_requirements() {
    print_step "Checking system requirements..."
    
    # Check Node.js
    if ! command -v node &> /dev/null; then
        print_error "Node.js is not installed. Please install Node.js 20+ from https://nodejs.org/"
    fi
    
    NODE_VERSION=$(node -v | cut -d'v' -f2)
    NODE_MAJOR=$(echo $NODE_VERSION | cut -d'.' -f1)
    if [ $NODE_MAJOR -lt 20 ]; then
        print_error "Node.js 20+ required. Found version $NODE_VERSION"
    fi
    print_success "Node.js $NODE_VERSION detected"
    
    # Check npm
    if ! command -v npm &> /dev/null; then
        print_error "npm is not installed"
    fi
    print_success "npm $(npm -v) detected"
    
    # Check git
    if ! command -v git &> /dev/null; then
        print_warning "Git is not installed. You'll need it for version control."
    else
        print_success "Git $(git --version | cut -d' ' -f3) detected"
    fi
    
    # Check Docker (optional but recommended)
    if command -v docker &> /dev/null; then
        print_success "Docker $(docker --version | cut -d' ' -f3 | cut -d',' -f1) detected"
        if command -v docker-compose &> /dev/null; then
            print_success "Docker Compose $(docker-compose --version | cut -d' ' -f3) detected"
        fi
    else
        print_warning "Docker not found - optional for containerized development"
    fi
    
    # Check PostgreSQL (optional)
    if command -v psql &> /dev/null; then
        print_success "PostgreSQL $(psql --version | cut -d' ' -f3) detected"
    else
        print_warning "PostgreSQL not found - will use Docker or remote database"
    fi
}

# Get project name
setup_project_name() {
    if [ -z "$1" ]; then
        print_step "No project name provided. Using 'my-app'"
        PROJECT_NAME="my-app"
    else
        PROJECT_NAME="$1"
    fi
    
    print_step "Creating project: $PROJECT_NAME"
}

# Create project structure
create_project_structure() {
    if [ -d "$PROJECT_NAME" ]; then
        print_error "Directory '$PROJECT_NAME' already exists. Please choose a different name."
    fi
    
    mkdir -p "$PROJECT_NAME"
    cd "$PROJECT_NAME"
    print_success "Created directory structure"
}

# Initialize Git repository
init_git() {
    print_step "Initializing Git repository..."
    git init > /dev/null 2>&1 || print_warning "Git initialization failed"
    
    cat > .gitignore << 'EOF'
# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# local env files
.env*.local
.env

# vercel
.vercel

# typescript
*.tsbuildinfo
next-env.d.ts

# prisma
prisma/*.db
prisma/*.db-journal
prisma/migrations/*.sql

# docker
*.pid
*.pid.lock

# logs
logs/
*.log

# Windows
Thumbs.db
desktop.ini
EOF
    
    print_success "Git initialized with .gitignore"
}

# Create package.json
create_package_json() {
    print_step "Creating package.json..."
    
    cat > package.json << EOF
{
  "name": "$PROJECT_NAME",
  "version": "0.1.0",
  "private": true,
  "description": "A production-grade application generated by shipready",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "type-check": "tsc --noEmit",
    "db:migrate": "prisma migrate dev",
    "db:deploy": "prisma migrate deploy",
    "db:seed": "tsx prisma/seed.ts",
    "db:studio": "prisma studio",
    "docker:up": "docker-compose up -d",
    "docker:down": "docker-compose down",
    "docker:logs": "docker-compose logs -f",
    "docker:build": "docker-compose build",
    "vercel:build": "npx prisma generate && npm run build"
  },
  "dependencies": {
    "@prisma/client": "5.14.0",
    "@radix-ui/react-avatar": "1.0.4",
    "@radix-ui/react-checkbox": "1.0.4",
    "@radix-ui/react-dialog": "1.0.5",
    "@radix-ui/react-dropdown-menu": "2.0.6",
    "@radix-ui/react-label": "2.0.2",
    "@radix-ui/react-popover": "1.0.7",
    "@radix-ui/react-select": "2.0.0",
    "@radix-ui/react-separator": "1.0.3",
    "@radix-ui/react-slot": "1.0.2",
    "@radix-ui/react-switch": "1.0.3",
    "@radix-ui/react-toast": "1.1.5",
    "@radix-ui/react-tooltip": "1.0.7",
    "@upstash/ratelimit": "0.3.4",
    "@upstash/redis": "1.27.0",
    "bcryptjs": "2.4.3",
    "class-variance-authority": "0.7.0",
    "clsx": "2.1.0",
    "lucide-react": "0.294.0",
    "next": "14.2.1",
    "next-auth": "5.0.0-beta.16",
    "pino": "8.19.0",
    "pino-pretty": "10.3.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-hook-form": "7.51.3",
    "react-email": "2.0.0",
    "resend": "3.0.0",
    "tailwind-merge": "2.2.0",
    "tailwindcss-animate": "1.0.7",
    "zod": "3.22.4"
  },
  "devDependencies": {
    "@types/bcryptjs": "2.4.6",
    "@types/node": "20.12.7",
    "@types/react": "18.2.79",
    "@types/react-dom": "18.2.25",
    "@typescript-eslint/eslint-plugin": "7.8.0",
    "@typescript-eslint/parser": "7.8.0",
    "autoprefixer": "10.4.19",
    "eslint": "8.57.0",
    "eslint-config-next": "14.2.1",
    "postcss": "8.4.38",
    "prisma": "5.14.0",
    "tailwindcss": "3.4.3",
    "tsx": "4.7.3",
    "typescript": "5.4.5"
  }
}
EOF
    
    print_success "package.json created"
}

# Create TypeScript configuration
create_tsconfig() {
    print_step "Creating TypeScript configuration..."
    
    cat > tsconfig.json << 'EOF'
{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
EOF
    
    print_success "tsconfig.json created"
}

# Create Next.js configuration
create_next_config() {
    print_step "Creating Next.js configuration..."
    
    cat > next.config.ts << 'EOF'
import type { NextConfig } from 'next'

const nextConfig: NextConfig = {
  output: 'standalone',
  images: {
    domains: [],
    formats: ['image/avif', 'image/webp'],
  },
  experimental: {
    optimizePackageImports: ['@radix-ui/react-icons', 'lucide-react'],
  },
  swcMinify: true,
  poweredByHeader: false,
  reactStrictMode: true,
  compress: true,
  compiler: {
    removeConsole: process.env.NODE_ENV === 'production',
  },
  redirects: async () => {
    return [
      {
        source: '/',
        destination: '/dashboard',
        permanent: true,
      },
    ]
  },
}

export default nextConfig
EOF
    
    print_success "next.config.ts created"
}

# Create Tailwind CSS configuration
create_tailwind_config() {
    print_step "Creating Tailwind CSS configuration..."
    
    cat > tailwind.config.ts << 'EOF'
import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
export default config
EOF
    
    print_success "tailwind.config.ts created"
}

# Create PostCSS configuration
create_postcss_config() {
    print_step "Creating PostCSS configuration..."
    
    cat > postcss.config.js << 'EOF'
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
EOF
    
    print_success "postcss.config.js created"
}

# Create ESLint configuration
create_eslint_config() {
    print_step "Creating ESLint configuration..."
    
    cat > .eslintrc.json << 'EOF'
{
  "extends": ["next/core-web-vitals", "plugin:@typescript-eslint/recommended"],
  "parser": "@typescript-eslint/parser",
  "plugins": ["@typescript-eslint"],
  "rules": {
    "@typescript-eslint/no-unused-vars": ["error", { "argsIgnorePattern": "^_" }],
    "@typescript-eslint/no-explicit-any": "error",
    "react-hooks/rules-of-hooks": "error",
    "react-hooks/exhaustive-deps": "warn",
    "no-console": ["warn", { "allow": ["error"] }]
  }
}
EOF
    
    print_success ".eslintrc.json created"
}

# Create environment variables
create_env_files() {
    print_step "Creating environment variable files..."
    
    cat > .env.example << 'EOF'
# Database
DATABASE_URL="postgresql://appuser:password@localhost:5432/appdb?schema=public"
POSTGRES_DB=appdb
POSTGRES_USER=appuser
POSTGRES_PASSWORD=password

# Authentication
NEXTAUTH_SECRET="generate-a-secret-with-openssl-rand-hex-32"
NEXTAUTH_URL="http://localhost:3000"
NEXTAUTH_URL_INTERNAL="http://app:3000"

# Rate Limiting (Upstash Redis)
UPSTASH_REDIS_REST_URL="https://your-redis.upstash.io"
UPSTASH_REDIS_REST_TOKEN="your-token"

# Email (Resend)
RESEND_API_KEY="re_your-api-key"
EMAIL_FROM="noreply@yourdomain.com"

# Stripe (if using payments)
STRIPE_SECRET_KEY="sk_test_..."
STRIPE_WEBHOOK_SECRET="whsec_..."

# AWS S3 (if using file uploads)
AWS_ACCESS_KEY_ID=""
AWS_SECRET_ACCESS_KEY=""
AWS_REGION="us-east-1"
AWS_S3_BUCKET=""

# Application
NODE_ENV=development
LOG_LEVEL=info
NEXT_PUBLIC_APP_URL="http://localhost:3000"
NEXT_PUBLIC_APP_NAME="My App"

# CORS
CORS_ORIGIN="http://localhost:3000,https://yourdomain.com"
EOF
    
    cat > .env.local.example << 'EOF'
# Development environment
# Copy this to .env.local and modify as needed
DATABASE_URL="postgresql://appuser:password@localhost:5432/appdb?schema=public"
POSTGRES_DB=appdb
POSTGRES_USER=appuser
POSTGRES_PASSWORD=devpassword

NEXTAUTH_SECRET="dev-secret-key-please-change-in-production"
NEXTAUTH_URL="http://localhost:3000"

NODE_ENV=development
LOG_LEVEL=debug
NEXT_PUBLIC_APP_URL="http://localhost:3000"
NEXT_PUBLIC_APP_NAME="My App (Dev)"
EOF
    
    print_success "Environment files created"
}

# Create Docker files
create_docker_files() {
    print_step "Creating Docker configuration..."
    
    cat > Dockerfile << 'EOF'
FROM node:20-alpine AS base

# Install dependencies only when needed
FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --only=production

# Build the application
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npx prisma generate
RUN npm run build

# Production image
FROM base AS runner
WORKDIR /app
ENV NODE_ENV production
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
USER nextjs
EXPOSE 3000
ENV PORT 3000
CMD ["node", "server.js"]
EOF
    
    cat > docker-compose.yml << 'EOF'
version: '3.9'

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
      POSTGRES_USER: ${POSTGRES_USER:-appuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-devpassword}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-appuser}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    command: npm run dev

volumes:
  postgres_data:
  redis_data:
EOF
    
    print_success "Docker files created"
}

# Create Prisma setup
create_prisma_setup() {
    print_step "Creating Prisma setup..."
    
    mkdir -p prisma
    
    cat > prisma/schema.prisma << 'EOF'
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id         String    @id @default(uuid())
  email      String    @unique
  password   String?   @db.Text
  name       String?
  role       Role      @default(USER)
  createdAt  DateTime  @default(now()) @map("created_at")
  updatedAt  DateTime  @updatedAt @map("updated_at")
  
  // Add your relationships here
  // posts Post[]
  
  @@map("users")
  @@index([email])
}

enum Role {
  USER
  ADMIN
}

// Add your models below
// model Post {
//   id        String   @id @default(uuid())
//   title     String
//   content   String?  @db.Text
//   published Boolean  @default(false)
//   authorId  String
//   author    User     @relation(fields: [authorId], references: [id], onDelete: CASCADE)
//   createdAt DateTime @default(now()) @map("created_at")
//   updatedAt DateTime @updatedAt @map("updated_at")
//   
//   @@map("posts")
//   @@index([authorId])
// }
EOF
    
    cat > prisma/seed.ts << 'EOF'
import { PrismaClient } from '@prisma/client'
import { hash } from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Seeding database...')

  // Create admin user
  const adminPassword = await hash('admin123', 10)
  const admin = await prisma.user.upsert({
    where: { email: 'admin@example.com' },
    update: {},
    create: {
      email: 'admin@example.com',
      password: adminPassword,
      name: 'Admin User',
      role: 'ADMIN',
    },
  })
  console.log(`👤 Created admin: ${admin.email}`)

  // Create regular user
  const userPassword = await hash('user123', 10)
  const user = await prisma.user.upsert({
    where: { email: 'user@example.com' },
    update: {},
    create: {
      email: 'user@example.com',
      password: userPassword,
      name: 'Regular User',
      role: 'USER',
    },
  })
  console.log(`👤 Created user: ${user.email}`)

  // Add your seed data here
  console.log('✅ Seeding complete!')
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
EOF
    
    print_success "Prisma setup created"
}

# Create source directory structure
create_source_structure() {
    print_step "Creating source directory structure..."
    
    dirs=(
        "src/app/api/health"
        "src/app/api/v1"
        "src/app/(auth)/login"
        "src/app/(auth)/register"
        "src/app/(dashboard)"
        "src/app/admin"
        "src/components/ui"
        "src/components/forms"
        "src/lib/validations"
        "src/lib/auth"
        "src/types"
        "src/hooks"
    )
    
    for dir in "${dirs[@]}"; do
        mkdir -p "$dir"
    done
    
    # Create app layout
    cat > src/app/layout.tsx << 'EOF'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from '@/components/ui/toaster'
import { AuthProvider } from '@/components/auth-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by shipready',
  metadataBase: new URL(process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'),
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          {children}
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  )
}
EOF
    
    # Create globals.css
    cat > src/app/globals.css << 'EOF'
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 222.2 84% 4.9%;
    --card: 0 0% 100%;
    --card-foreground: 222.2 84% 4.9%;
    --popover: 0 0% 100%;
    --popover-foreground: 222.2 84% 4.9%;
    --primary: 221.2 83.2% 53.3%;
    --primary-foreground: 210 40% 98%;
    --secondary: 210 40% 96.1%;
    --secondary-foreground: 222.2 47.4% 11.2%;
    --muted: 210 40% 96.1%;
    --muted-foreground: 215.4 16.3% 46.9%;
    --accent: 210 40% 96.1%;
    --accent-foreground: 222.2 47.4% 11.2%;
    --destructive: 0 84.2% 60.2%;
    --destructive-foreground: 210 40% 98%;
    --border: 214.3 31.8% 91.4%;
    --input: 214.3 31.8% 91.4%;
    --ring: 221.2 83.2% 53.3%;
    --radius: 0.5rem;
  }

  .dark {
    --background: 222.2 84% 4.9%;
    --foreground: 210 40% 98%;
    --card: 222.2 84% 4.9%;
    --card-foreground: 210 40% 98%;
    --popover: 222.2 84% 4.9%;
    --popover-foreground: 210 40% 98%;
    --primary: 217.2 91.2% 59.8%;
    --primary-foreground: 222.2 47.4% 11.2%;
    --secondary: 217.2 32.6% 17.5%;
    --secondary-foreground: 210 40% 98%;
    --muted: 217.2 32.6% 17.5%;
    --muted-foreground: 215 20.2% 65.1%;
    --accent: 217.2 32.6% 17.5%;
    --accent-foreground: 210 40% 98%;
    --destructive: 0 62.8% 30.6%;
    --destructive-foreground: 210 40% 98%;
    --border: 217.2 32.6% 17.5%;
    --input: 217.2 32.6% 17.5%;
    --ring: 224.3 76.3% 48%;
  }
}

@layer base {
  * {
    @apply border-border;
  }
  body {
    @apply bg-background text-foreground;
  }
}
EOF
    
    # Create health check
    cat > src/app/api/health/route.ts << 'EOF'
import { prisma } from '@/lib/prisma'
import { NextResponse } from 'next/server'
import { logger } from '@/lib/logger'

export async function GET() {
  try {
    await prisma.$queryRaw`SELECT 1`
    
    return NextResponse.json({
      status: 'ok',
      timestamp: new Date().toISOString(),
      database: 'connected',
      version: process.env.npm_package_version ?? '0.1.0',
      environment: process.env.NODE_ENV,
    })
  } catch (error) {
    logger.error({ error }, 'Health check failed')
    
    return NextResponse.json(
      {
        status: 'error',
        timestamp: new Date().toISOString(),
        database: 'disconnected',
        error: 'Database connection failed',
      },
      { status: 503 }
    )
  }
}
EOF
    
    print_success "Source structure created"
}

# Create essential lib files
create_lib_files() {
    print_step "Creating library files..."
    
    # Prisma client
    cat > src/lib/prisma.ts << 'EOF'
import { PrismaClient } from '@prisma/client'
import { logger } from './logger'

const globalForPrisma = globalThis as unknown as { prisma: PrismaClient }

export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    log: [
      { emit: 'event', level: 'query' },
      { emit: 'event', level: 'error' },
      { emit: 'event', level: 'warn' },
    ],
  })

prisma.$on('error', (e) => {
  logger.error({ err: e }, 'Prisma error')
})

prisma.$on('warn', (e) => {
  logger.warn({ err: e }, 'Prisma warning')
})

if (process.env.NODE_ENV !== 'production') {
  globalForPrisma.prisma = prisma
}
EOF
    
    # Logger
    cat > src/lib/logger.ts << 'EOF'
import pino from 'pino'

export const logger = pino({
  level: process.env.LOG_LEVEL ?? 'info',
  redact: ['password', 'token', 'secret', 'authorization', 'cookie', '*.password'],
  ...(process.env.NODE_ENV !== 'production' && {
    transport: {
      target: 'pino-pretty',
      options: {
        colorize: true,
        translateTime: 'HH:MM:ss',
        ignore: 'pid,hostname',
      },
    },
  }),
})
EOF
    
    # Environment validation
    cat > src/lib/env.ts << 'EOF'
import { z } from 'zod'

const envSchema = z.object({
  DATABASE_URL: z.string().url(),
  NEXTAUTH_SECRET: z.string().min(32),
  NEXTAUTH_URL: z.string().url(),
  NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
  LOG_LEVEL: z.enum(['debug', 'info', 'warn', 'error']).default('info'),
  NEXT_PUBLIC_APP_URL: z.string().url().default('http://localhost:3000'),
  NEXT_PUBLIC_APP_NAME: z.string().default('My App'),
  CORS_ORIGIN: z.string().optional().default('http://localhost:3000'),
  
  // Optional but recommended
  UPSTASH_REDIS_REST_URL: z.string().url().optional(),
  UPSTASH_REDIS_REST_TOKEN: z.string().optional(),
  RESEND_API_KEY: z.string().optional(),
  EMAIL_FROM: z.string().email().optional(),
})

const _env = envSchema.safeParse(process.env)

if (!_env.success) {
  console.error('❌ Invalid environment variables:\n', _env.error.format())
  process.exit(1)
}

export const env = _env.data
EOF
    
    # Rate limiting
    cat > src/lib/rate-limit.ts << 'EOF'
import { Ratelimit } from '@upstash/ratelimit'
import { Redis } from '@upstash/redis'
import { env } from './env'

let ratelimit: Ratelimit | null = null

if (env.UPSTASH_REDIS_REST_URL && env.UPSTASH_REDIS_REST_TOKEN) {
  const redis = new Redis({
    url: env.UPSTASH_REDIS_REST_URL,
    token: env.UPSTASH_REDIS_REST_TOKEN,
  })

  ratelimit = new Ratelimit({
    redis,
    limiter: Ratelimit.slidingWindow(5, '15m'),
    analytics: true,
    prefix: 'ratelimit',
  })
}

export const rateLimit = ratelimit
EOF
    
    print_success "Library files created"
}

# Create README
create_readme() {
    print_step "Creating README.md..."
    
    cat > README.md << EOF
# $PROJECT_NAME

A production-grade application generated by **shipready** — a complete, deploy-ready codebase with security, database, error handling, API design, environment, performance, frontend, and DevOps baked in from line one.

## 🚀 Tech Stack

- **Framework:** Next.js 14 (App Router)
- **Language:** TypeScript (strict mode)
- **Database:** PostgreSQL with Prisma ORM
- **Auth:** NextAuth.js v5
- **Styling:** Tailwind CSS
- **Forms:** react-hook-form + Zod
- **Logging:** Pino
- **Rate Limiting:** Upstash Redis
- **Email:** Resend + react-email
- **Deployment:** Vercel (primary) + Docker

## 📋 Prerequisites

- Node.js 20+
- npm 9+
- PostgreSQL 16+ (or Docker)
- Git

## 🛠️ Quick Setup

1. **Clone the repository:**
   \`\`\`bash
   git clone <your-repo-url>
   cd $PROJECT_NAME
   \`\`\`

2. **Install dependencies:**
   \`\`\`bash
   npm install
   \`\`\`

3. **Set up environment variables:**
   \`\`\`bash
   cp .env.local.example .env.local
   # Edit .env.local with your values
   \`\`\`

4. **Start the database (with Docker):**
   \`\`\`bash
   npm run docker:up
   \`\`\`

5. **Run database migrations:**
   \`\`\`bash
   npm run db:migrate
   \`\`\`

6. **Seed the database:**
   \`\`\`bash
   npm run db:seed
   \`\`\`

7. **Start the development server:**
   \`\`\`bash
   npm run dev
   \`\`\`

   Your app is now running at **http://localhost:3000**

## 🔑 Default Admin Credentials

- **Email:** admin@example.com
- **Password:** admin123

**Please change these credentials immediately in production!**

## 📦 Available Scripts

| Command | Description |
|---------|-------------|
| \`npm run dev\` | Start development server |
| \`npm run build\` | Build for production |
| \`npm run start\` | Start production server |
| \`npm run lint\` | Run ESLint |
| \`npm run type-check\` | Type check TypeScript |
| \`npm run db:migrate\` | Run database migrations |
| \`npm run db:deploy\` | Deploy migrations to production |
| \`npm run db:seed\` | Seed database with initial data |
| \`npm run db:studio\` | Open Prisma Studio |
| \`npm run docker:up\` | Start Docker containers |
| \`npm run docker:down\` | Stop Docker containers |
| \`npm run docker:build\` | Build Docker image |

## 🏗️ Project Structure

\`\`\`
$PROJECT_NAME/
├── src/
│   ├── app/               # Next.js App Router
│   │   ├── (auth)/        # Authentication routes
│   │   │   ├── login/
│   │   │   └── register/
│   │   ├── (dashboard)/   # Dashboard routes
│   │   ├── admin/         # Admin panel
│   │   ├── api/           # API routes
│   │   │   ├── health/    # Health check
│   │   │   │   └── route.ts
│   │   │   └── v1/        # Versioned API
│   │   ├── globals.css    # Global Tailwind styles
│   │   └── layout.tsx     # Root layout
│   ├── components/        # React components
│   │   ├── ui/            # UI components
│   │   └── forms/         # Form components
│   ├── hooks/             # Custom React hooks
│   ├── lib/               # Utility functions and clients
│   │   ├── auth.ts        # Auth configuration
│   │   ├── env.ts         # Zod environment schema
│   │   ├── logger.ts      # Pino logger configuration
│   │   ├── prisma.ts      # Prisma client instance
│   │   └── rate-limit.ts  # Upstash rate limiting
│   └── types/             # TypeScript types
└── prisma/                # Prisma ORM schema and migrations
    ├── schema.prisma
    └── seed.ts
\`\`\`
EOF

    print_success "README.md created"
}

# Main execution flow
check_requirements
setup_project_name "$1"
create_project_structure
init_git
create_package_json
create_tsconfig
create_next_config
create_tailwind_config
create_postcss_config
create_eslint_config
create_env_files
create_docker_files
create_prisma_setup
create_source_structure
create_lib_files
create_readme

print_step "Installing dependencies..."
npm install

print_success "Project '$PROJECT_NAME' created successfully!"
echo -e "\nTo get started:"
echo -e "  cd $PROJECT_NAME"
echo -e "  npm run dev\n"
